development:
  adapter: postgresql
  database: db/jumpstarter_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: db/jumpstarter_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/jumpstarter_production
  pool: 5
  timeout: 5000
